"""
Seed semua dosen/pengajar ke tabel lecturers.
Jalankan: python seed_lecturers.py
"""
from app import create_app
from app.extensions import db
from app.models.lecturer import Lecturer

app = create_app()

LECTURERS = [
    # ── Guru Besar / Profesor ──
    "Prof. Dr. A. B. Takko, M.Hum.",
    "Prof. Dr. Abdul Hakim, M.Hum.",
    "Prof. Dr. Akin Duli, M.A.",
    "Prof. Dr. Andi Muhammad Akhmar, S.S., M.Hum.",
    "Prof. Dr. Asriani Abbas, M.Hum.",
    "Prof. Dr. Fathu Rahman, M.Hum.",
    "Prof. Dr. Gusnawaty, M.Hum.",
    "Prof. Dr. Harlinah Sahib, M.Hum.",
    "Prof. Dr. Herawaty, M.Hum., Ph.D.",
    "Prof. Dr. Kamsinah, M.Hum.",
    "Prof. Dr. Lukman, M.S.",
    "Prof. Dr. M. Amir P., M.Hum.",
    "Prof. Dr. Muhammad Darwis, M.Hum.",
    "Prof. Dr. Muhammad Hasyim, M.Si.",
    "Prof. Dr. Muhlis Hadrawi, S.S., M.Hum.",
    "Prof. Dr. Munira Hasjim, S.S., M.Hum.",
    "Prof. Dr. Nasmilah, M.Hum.",
    "Prof. Dr. Noer Jihad Saleh, M.Hum.",
    "Prof. Dr. Nurhayati, M.Hum.",
    "Prof. Dr. Nurhayati Rahman, M.S.",
    "Prof. Dr. Yusring Sanusi B, S.S., M.App.Ling.",
    "Prof. Drs. Burhanuddin Arafah, M.Hum., Ph.D.",
    "Prof. Wan Wen Bin",
    "Prof. Wu Xiao Ling",

    # ── Dosen Bergelar Doktor ──
    "Dr. Abbas, S.S., M.Hum.",
    "Dr. Abidin Pammu, M.A.",
    "Dr. Ade Yolanda Latjuba, S.S., M.A.",
    "Dr. Andi Agussalim, M.Hum.",
    "Dr. Andi Faisal, S.S., M.Hum.",
    "Dr. Ayub Khan, M.Si.",
    "Dr. Dafirah, M.Hum.",
    "Dr. Dirk Rukka Sandarupa, S.S., M.Hum.",
    "Dr. Drs. H. M. Dahlan Abubakar, M.Hum.",
    "Dr. Erni Erawati, M.Si.",
    "Dr. Ery Iswary, M.Hum.",
    "Dr. Fierenziana Getruida Junus, S.S., M.Hum.",
    "Dr. H. Ahmad Mujahid, M.Ag.",
    "Dr. Haryeni, M.Hum.",
    "Dr. Hasanuddin, M.Hum.",
    "Dr. Hj. Indarwati, S.S., M.Hum.",
    "Dr. Ida Liana Tanjung, M.Hum.",
    "Dr. Ikhwan Sumantri, M.Hum.",
    "Dr. Ilham Alimuddin, S.T., M.GIS.",
    "Dr. Ilham, S.S., M.Hum.",
    "Dr. Imelda, S.S., M.Pd.",
    "Dr. Indriati Lewa, M.Hum.",
    "Dr. Kaharuddin, M.Hum.",
    "Dr. Karmila Mokoginta, S.S., M.Hum.",
    "Dr. Khadijah Thahir Muda, M.Si.",
    "Dr. M. Dalyan Tahir, M.Hum.",
    "Dr. Mardi Adi Armin, M.Hum.",
    "Dr. Muhammad Bahar Akase Teng, LCP, M.Hum.",
    "Dr. Muhammad Nur, S.S., M.A.",
    "Dr. Mulyani, S.Pd., M.Pd.",
    "Dr. Muslimat, M.Hum.",
    "Dr. Muslimin A. R. Effendy, M.A.",
    "Dr. Nahdia Nur, M.Hum.",
    "Dr. Nursidah, S.Pd., M.Pd.",
    "Dr. Prasuri Kuswarini, M.A.",
    "Dr. Pratiwi Bahar, S.S., M.Hum.",
    "Dr. Rosmawati, S.S., M.Si.",
    "Dr. Sitti Sahraeny, S.S., M.Hum.",
    "Dr. Sitti Wahidah Masnani, M.Hum.",
    "Dr. Sukmawaty, M.Hum.",
    "Dr. Sumarlin Rengko H. R., S.S., M.Hum.",
    "Dr. Supriadi, S.S., M.A.",
    "Dr. Suriadi Mappangara, M.Hum.",
    "Dr. Syamsul Bahri Abd. Hamid, L.C., M.A.",
    "Dr. Tammasse, M.Hum.",
    "Dr. Wahyuddin, S.S., M.Hum.",
    "Dr. Yadi Mulyadi, S.S., M.A.",
    "Dr. Zuhriah, S.S., M.Hum.",

    # ── Dosen JFU / Luar Biasa ──
    "A. Bahrul Hidayah, S.T., M.T.",
    "A. Meirling, S.S., M.Hum.",
    "A. Muh. Saiful, S.S., M.A.",
    "Ainun Fatimah, S.S., M.Hum.",
    "Alung, S.S., M.A.",
    "Amrullah Amir, S.S., M.A., Ph.D.",
    "Andi Filsah Muslimat, S.S., M.Hum.",
    "Andi Inayah Soraya, S.S., M.Hum.",
    "Andi Tenri Bali Baso, S.S., M.Hum.",
    "Andi Wardatul Wahidah Lufini, S.Pd., M.A.",
    "Aqilah Nurul Khaerani Latif, S.E., M.Par.",
    "Asmuliyati Nahnu, S.S., M.CIE.",
    "Ayu Azhariyah, S.E., S.S., Ak., M.A.",
    "Basiah, S.S., M.A.",
    "Burhan Kadir, S.S., M.A.",
    "Chen Dandan",
    "Dian, S.S., M.Hum.",
    "Dian Rahmawati Arief, S.S., M.Hum.",
    "Dian Sari Unga Waru, S.S., M.TCSOL.",
    "Dra. Irianty Bandu, M.Pd.",
    "Dra. Marleny Rajuni, M.Ed.",
    "Dra. Nadira Mahaseng, M.Ed.",
    "Dra. Ria Rosdiana Jubhari, M.A., Ph.D.",
    "Dra. St. Nursa'adah, S.S., M.Hum.",
    "Drs. Abd. Rasyid R., M.Ag.",
    "Drs. Dias Pradadmara, M.A.",
    "Drs. H. Hamris Darwis, M.Si.",
    "Drs. Hasbullah, M.Hum.",
    "Drs. Husain Hasyim, M.Hum.",
    "Drs. Laode Muhammad Aksa, M.Hum.",
    "Drs. Simon Sitoto, M.A.",
    "Drs. Yusuf, S.U.",
    "Erwin Mansyur Ugu Saraka, S.S., M.Sc.",
    "Fadhillah Duli, S.I.Kom., M.Si.",
    "Fadlan Ahmad, S.S., M.Si.",
    "Fahran Reza, S.S., M.Hum.",
    "Faisal Oddang, S.S., M.Hum.",
    "Fajar Sidiq Limola, S.S., M.Hum.",
    "Fakhreny Fathu Rahman, S.S., M.Si.",
    "Fakhriawan Fathu Rahman, S.S., M.Litt.",
    "Fithyani Anwar, S.S., M.A., Ph.D.",
    "Fitriani, S.S., M.Hum.",
    "Hadi Hidayat, S.S., M.Hum.",
    "Haeriyyah, S.Ag., M.Pd.I.",
    "Haeruddin, S.S., M.A.",
    "Haruna Fukuda",
    "Hidayatullah Yunus, S.S., M.TESOL.",
    "Hunaeni, S.S., M.Si.",
    "Ilham, S.S., M.Hum.",
    "Indra Mayanti Noer, S.S., M.Hum.",
    "Kasmawati, S.S., M.Hum.",
    "Khaeruddin, M.Hum., Ph.D.",
    "Khafifa Fuji Lestari, S.Pd., M.Ed.",
    "Khairil Anwar, S.S., M.A.",
    "Leni Cahyati, S.S., M.CIE.",
    "Masdiana, S.S., M.Hum.",
    "Meta Sekar Puji Astuti, S.S., M.A., Ph.D.",
    "Muh. Ridha Anugrah, S.S., M.Hum.",
    "Muhammad Nur Iman, S.S., M.Hum.",
    "Muhammad Ridwan, S.S., M.A.",
    "Muhammad Syachrun Sjam, S.S., M.Hum.",
    "Mujadilah Nur, S.S., M.Hum.",
    "Mutahharah Nemin Kaharuddin, S.S., M.Hum.",
    "Nasihin, S.S., M.A.",
    "Nirdayanti M., S.S., M.CIE.",
    "Nur Rahmiani Achmad, S.IP., M.M.Par.",
    "Nur Syam, S.S., M.Hum.",
    "Nurfitri, S.S., M.Hum.",
    "Pammuda, S.S., M.Si.",
    "Rafika Hayati, S.ST.Par., M.Par.",
    "Rezky Ramadhani, S.S., M.Litt.",
    "Riska Faradilla Nazar, S.S., M.Hum.",
    "Rismayanti, S.S., M.Hum.",
    "Rizqi Awalia Ilma, S.S., M.TCSOL.",
    "Shen Su Jia",
    "Supratman, S.S., M.A.",
    "Suryatman, S.S., M.Hum.",
    "Syahwan Alfianto Amir, S.S., M.Hum.",
    "Taqdir, S.Pd., M.Hum.",
    "Wa Ode Sitti Hardianti Halidun, S.S., M.A.",
    "Yunita Tetta Dendo, S.S., M.CIE.",
    "Yusriana, S.S., M.A.",
    "Zhu Tong Xin",
]


with app.app_context():
    existing = {l.lecturer_name.strip().lower() for l in Lecturer.query.all()}
    added = 0
    skipped = 0

    for name in LECTURERS:
        if name.strip().lower() in existing:
            skipped += 1
            continue
        db.session.add(Lecturer(lecturer_name=name.strip()))
        added += 1

    db.session.commit()
    print(f"Selesai: {added} dosen ditambahkan, {skipped} dilewati (sudah ada).")
    print(f"Total dosen di DB: {Lecturer.query.count()}")
