"""empty message

Revision ID: 1394773d1df1
Revises: 768d1e1f0b5f
Create Date: 2026-03-10 10:45:59.027594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1394773d1df1'
down_revision = '768d1e1f0b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('course_name', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['course_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('course_name')
        batch_op.drop_column('course_code')

    # ### end Alembic commands ###
