"""add_event_booking_holiday_pakta_approval_roles

Revision ID: 2552279dd0a0
Revises: 7c1d9b8a2f10
Create Date: 2026-05-31 17:17:16.155951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2552279dd0a0'
down_revision = '7c1d9b8a2f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('pakta_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('submission_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('name_on_pakta', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('pakta_integritas_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('surat_permohonan_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_fib_student', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_bem_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('staff_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejection_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('rejection_note')
        batch_op.drop_column('staff_note')
        batch_op.drop_column('is_bem_verified')
        batch_op.drop_column('is_fib_student')
        batch_op.drop_column('surat_permohonan_path')
        batch_op.drop_column('pakta_integritas_path')
        batch_op.drop_column('name_on_pakta')
        batch_op.drop_column('submission_date')
        batch_op.drop_column('booking_type')

    op.drop_table('pakta_templates')
    op.drop_table('holidays')
    # ### end Alembic commands ###
