"""empty message

Revision ID: 4aeedfd523d4
Revises: 6a33586267a5
Create Date: 2026-03-10 16:52:02.206981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4aeedfd523d4'
down_revision = '6a33586267a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_time', sa.Time(), nullable=True))
        batch_op.drop_constraint(batch_op.f('class_schedules_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('class_schedules_ibfk_5'), type_='foreignkey')
        batch_op.drop_column('time_slot_id')
        batch_op.drop_column('day_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('time_slot_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('class_schedules_ibfk_5'), 'time_slots', ['time_slot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('class_schedules_ibfk_2'), 'days', ['day_id'], ['id'])
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('schedule_date')

    # ### end Alembic commands ###
