"""empty message

Revision ID: ad834f909ce5
Revises: 4aeedfd523d4
Create Date: 2026-03-10 17:06:50.816951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad834f909ce5'
down_revision = '4aeedfd523d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_name', sa.String(length=20), nullable=True))
        batch_op.drop_column('schedule_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_date', sa.DATE(), nullable=True))
        batch_op.drop_column('day_name')

    # ### end Alembic commands ###
